# Generated by Django 6.0.6 on 2026-06-15 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='reg_number',
            field=models.IntegerField(null=True),
        ),
    ]
